module.exports = Object.freeze({
  MODAL_BODY_TYPES: {
    USER_DETAIL: "USER_DETAIL",
    LEAD_ADD_NEW: "LEAD_ADD_NEW",
    ADD_PHONEBOOK: "ADD_PHONEBOOK",
    ADD_TASK: "ADD_TASK",
    ADD_TASK_ALL: "ADD_TASK_ALL",
    REPORT_TASK: "REPORT_TASK",
    CREATE_GROUP: "CREATE_GROUP",
    ADD_MEMBER_GROUP: "ADD_MEMBER_GROUP",
    CONFIRMATION: "CONFIRMATION",
    UPDATE_NAME_CONTACT: "UPDATE_NAME_CONTACT",
    DEFAULT: "",
  },

  RIGHT_DRAWER_TYPES: {
    NOTIFICATION: "NOTIFICATION",
    CALENDAR_EVENTS: "CALENDAR_EVENTS",
    INFO_ROOM: "INFO_ROOM",
  },

  CONFIRMATION_MODAL_CLOSE_TYPES: {
    LEAD_DELETE: "LEAD_DELETE",
    DELETE_CONTACT: "DELETE_CONTACT",
    DELETE_TASK: "DELETE_TASK",
    DELETE_MEMBER_GROUP: "DELETE_MEMBER_GROUP"
  },
});
